<?php

/**
 * @file
 * Commerce Pickup - Install
 */

/**
 * Implements hook_uninstall().
 */
function commerce_pickup_uninstall() {

  // Delete variables.
  variable_del('commerce_pickup_location_entity');
  variable_del('commerce_pickup_service_display_title');
  variable_del('commerce_pickup_location_list_element');
  variable_del('commerce_pickup_location_list_description');
}

/**
 * Update to use individual shipping services.
 */
function commerce_pickup_update_7000(&$sandbox) {

  // Originally, this module provided a single shipping service.
  // This code updates it to a new scheme whereby a shipping service
  // is provided for each pickup location entity.

  // Load all entries from the {commerce_pickup_line_item} table.
  $query = db_select('commerce_pickup_line_item', 'p');
  $query->fields('p');
  $results = $query->execute();

  // Iterate through the results.
  foreach ($results as $result) {

    // Load the line item.
    $line_item = commerce_line_item_load($result->line_item_id);

    // Load the display title of the pickup services.
    $pickup_title = variable_get('commerce_pickup_service_display_title', 'Pickup');

    // Set the line item label to the new format.
    $line_item->line_item_label = t('@pickup at @location', array('@pickup' => $pickup_title, '@location' => $result->label));

    // Save the line item.
    commerce_line_item_save($line_item);
  }

  // Remove the old database table.
  db_drop_table('commerce_pickup_line_item');

  // Rebuild the menus.
  menu_rebuild();

  // Return a message.
  return t('Commerce Pickup has been updated to use individual shipping services.');
}
